is_debug: true
listen:
  type: port
  port: 3000
storage:
  host: 127.0.0.1
  port: 5432
  database: hil_hojalyk
  username: postgres
  password: 1234
  pg_pool_max_conn: 10
jwt_key: buzgaymak50tenne
socket_jwt_key: buzgaymak50tenne
app_version: 0.0.1
max_file_size: 10485760
